---
repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: terraform-fmt
      - id: tflint
        args:
          - "--module"
          - "--config=.tflint.hcl"
      #- id: markdown-link-check

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.76.0
    hooks:
      - id: terraform_tfsec
        args:
          - >
            --args=--soft-fail
      - id: terraform_docs